spring.application.name=validation

spring.datasource.url=jdbc:postgresql://localhost:5432/validation 

spring.datasource.username=postgres

# M?t kh?u m? c?a kho
spring.datasource.password=vietanh2k5

# Yêu c?u Spring hi?n câu l?nh SQL ra màn hình console
spring.jpa.show-sql=true

# Không ?? Spring t? ??ng s?a ??i b?ng trong DB
spring.jpa.hibernate.ddl-auto=update